module.exports = {
  folderMovies: 'F:/movies',
  findTeach: 'have a nice',
  start: '0:0:0',
  times: [
    ['1:6:11', '1:6:59'],
    ['1:22:59', '1:24:0'],
    ['0:55:49', '0:56:22'],
    ['0:8:10', '0:8:41'],
    ['0:10:53', '0:11:33'],
    ['0:23:8', '0:23:32'],
    ['0:31:42', '0:32:15'],
    ['0:59:33', '1:0:7'],
  ],
  path: 'F:/movies/Home Alone 2 Lost in New York (1992)',
  teaches: [
    "Where'd he go",
    "I'm up here",
    'Hold on',
    'got busted',
    'underestimated',
    "This ain't like that",
    "This ain't his house",
    'running scared',
    "He ain't got a plan",
    'May I do the thinking',
    'Nothing would thrill me more greatly than to shoot you.',
    // "Knocking off",
    "But since we're in a hurry",
    'throw down',
    "we won't hurt you",
    "You'll never hear from us again",
  ],
}
