require('./js/warning')
require('./js/repetitionVideo')
require('./js/mostFastSentence')
require('./js/velocityControl')
require('./js/searchSentence')
require('./player')
require('./js/controlF')
require('./js/video')
require('./js/controls')
require('./js/syncVideoSubtitle')
require('./js/changeTimeVideo')
require('./js/editSrt')
require('./js/dynamicallyVelocity')
require('./js/info')
require('./js/gameToWatch')
require('./js/saveClip')
require('./js/checkPoint')
// require('./js/clips')
require('./js/lyrics')
// require('./player.js')

require('./js/handleVideoConfig')
